name: publish-nuget

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore "./dotnet/XHale.Core/XHale.Core.csproj"

      - name: Clean artifacts
        run: rm -rf ./artifacts && mkdir -p ./artifacts

      - name: Pack
        run: dotnet pack "./dotnet/XHale.Core/XHale.Core.csproj" -c Release -o ./artifacts

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate


